version: '2'

services:
  logstash-grafana:
    build: logstash/
    command: -f /etc/logstash/conf.d/
    volumes:
      - ./logstash/config:/etc/logstash/conf.d
    ports:
      - "5000:5000"
    networks:
      - docker_grafana

networks:
  docker_grafana:
    driver: bridge
